### ISSUE TITLE
Сделать кнопки чекбоксов видимыми всегда

### ISSUE THREAD

**Issue by nerlihmax** [kheynov/ToDoListApp#1]
<img width="254" alt="Снимок экрана 2021-11-03 в 00 32 56" src="https://user-images.githubusercontent.com/17108273/139916384-bf42df94-15e5-4f08-9476-415fc29e110b.png">
Кнопки чекбоксов невидимые в неактивном состоянии, что может запутать.

**Comment by kheynov** [comment]
fixed by commit 46146f56d92c8b1540db543ed04749b6510f4526
