### ISSUE TITLE
Подтверждение по событию с клавиатуры

### ISSUE THREAD

**Issue by nerlihmax** [kheynov/ToDoListApp#2]
<img width="459" alt="Снимок экрана 2021-11-03 в 00 35 05" src="https://user-images.githubusercontent.com/17108273/139916630-2c39156a-5eb1-4f9a-8d9a-b0f23cce532f.png">
Нужно иметь возможность сохранить новый таск по кнопки Enter на клавиатуре.
Так же можно задуматься над тем, что бы поднимать fab-кнопку так, что бы она располагалась над клавиатурой.

**Comment by kheynov** [comment]
UI добавления ToDo элемента переработано в коммите ae2bc57d037118d418f39bfc60e32b2c6fcc20c7
