### ISSUE TITLE
Изменение меню сортировки

### ISSUE THREAD

**Issue by nerlihmax** [kheynov/ToDoListApp#3]
<img width="399" alt="Снимок экрана 2021-11-03 в 00 42 30" src="https://user-images.githubusercontent.com/17108273/139917683-c4c42306-141f-42d4-9b83-cf04bf6ecb6c.png">
Предлагаю заменить чекбоксы Ascending и Descending на соответствующие кнопки-иконки.
А строку с фильтрами развернуть по вертикали.
Позже свое предложение дополню макетом.

**Comment by kheynov** [comment]
UI меня сортировки изменено в коммите 56a3a38b
